### ISSUE TITLE
Restructure v2.5

### ISSUE THREAD

**Issue by jokoho48** [nk3nny/LambsDanger#111]
The Restructure is meant to clean the file/code structure and move functions that are not just used by one Module and are not module specific into the main module. while that we also should clean and move duplicated stringtable entries into main to keep the stringtables as small as possible.

# Functions
- [x] Debug?
  - [x] DebugLog
  - [x] DebugObjectColor
- [x] doCallout
- [x] gesture -> doGesture
- [x] doSmoke
- [x] doUGL
- [x] eventCallback
- [x] findBuilding
- [x] findCover
- [x] nearbyFriendly -> findNearbyFriendly
- [x] findOverwatch
- [x] findReadyUnits
- [x] isAlive
- [x] indoor -> isIndoor
- [x] isNight

# Settings
- [x] Debug
- [x] Gesture
- [x] Callout

# Stringtable
- [x] Debug Settings
- [x] Gesture Settings
- [x] Callout Settings
- [ ] ~~Unify Duplicated Entrys~~

**Comment by nk3nny** [comment]
Stringtalbe

**Comment by nk3nny** [comment]
From meeting 
1. Look into adding relevant ACE3 animations when available (for gestures and so on)
2. Consider also restructuring fsm 
3. Suppressive fire module 
4. Supportive CAS 
5. Initial AI profiles (Forward Observer, Recon, Militia/Rebels) 
6.

**Comment by nk3nny** [comment]
With restructure consider renaming: 
- [ ]  fnc_gesture to fnc_doGesture
- [ ]  fnc_coward to fnc_isCoward

**Comment by nk3nny** [comment]
Reminder for self: 

Consider implementing a mod-wide disabling of _enableAttack_ to give us better fine control of AI attack patterns.  Units with the _currentCommand_ "ATTACK" become wildly moody and difficult to manoeuvre with. 

This would be an invasive change. 

https://community.bistudio.com/wiki/enableAttack
https://community.bistudio.com/wiki/currentCommand

**Comment by nk3nny** [comment]
Memo to self: 
Possibly add a CBA option which stops units given WP/Modules from changing ACE3 style headless swapping.

**Comment by nk3nny** [comment]
Add module which give a group the vanilla guard waypoint (and whatever enhancements we can provide or add to it).  Possibly adding a second module to define new guard positions.

**Comment by nk3nny** [comment]
**Small bugs**: 
- [ ] Units set to careless should exit FSM  (modify isForced and brainForced.sqf
- [ ] It seems units are sometimes "locked" into a dodge cycle. This causes them to permanently backpedal.  Will investigate

**Suppression**
Units are currently very suppression-happy. Will consider changing brainEngage to only allow "Can Fire" to trigger doSuppression, rather than also "Enemy Near". 

Have noticed AI will sometimes suppress quite happily at nothings. Though this may be related to other features. 

**lambs_danger_CQB**
The group variable "lambs_danger_CQB" is I think poorly named. A better reflection of it being a _sympathetic_ storeroom of positions to check or suppress would be "lambs_danger_memory" or similar.  Perhaps write a function which makes reading and modifying the variable easier.

**Comment by nk3nny** [comment]
**Todo**
- [ ]  rename shareInformation to doShareInformation
- [ ]  rename shareInformationRange to getShareInformationParams
- [ ]  move all "do*" functions to /main
- [ ]  move relevant EHs to main/wp
- [ ]  use internal EHs in /danger to readd reinforcement system
- [ ]  optionally add wrappers for moved EHs
- [ ]  fix known bugs (see below)
- [ ]  write changelog
- [ ]  test release
- [ ]  release

**Found bugs - 08.02.21**
- [ ]  	vehicle.sqf -- should exit if unit unconscious
- [ ]  	vehicleSuppress.sqf -- error with AGLtoASL handling

**Comment by nk3nny** [comment]
https://github.com/nk3nny/LambsDanger/pull/174

**Comment by nk3nny** [comment]
*Internal variable name change: lambs_main_isArtillery*
 - updated brainVehicle.sqf
 - updated leaderStaticDeploy
