### ISSUE TITLE
Implement: fn_taskAssault, fn_taskRetreat 

### ISSUE THREAD

**Issue by nk3nny** [nk3nny/LambsDanger#44]
As per earlier discussion. This is the last milestone features to complete for 2.0 beyond testing and final performance touches.  It is set to replace **fn_taskAttack** which currently exists in the framework. 

**fn_taskAssault** is proving to be an interesting challenge.  There are two versions of it implemented in the last pull request. One which leverages a per-frame eventhandler to facilitate movement.  The other which relies on recursive cba_waitAndExecutes.  The first option is currently chosen for the advantage of ease of updating destination by plodding down new waypoints, I imagine particularly in a ZEUS situation. 

The current implementation can however be optimised. Which is what this ISSUE thread is all about: **How to best implement and optimise**
1. Particular challenge:  _Interrupting WP with new WPs_
2. Particular challenge: _Kicking AI out of 'ATTACK' command state_

The current implementation provides an answer to both of these. However I expect that this can be cleaned up.  Hence looking for aid or comments. 

**fn_taskRetreat** is simply a variant of fn_taskAssault with one important difference. It should put the AI in a panicked set of animations and need not be interruptible in the same manner-- though being able to do so would be nice. fn_taskRetreat may as a further option have a random chance of AI dropping weapons and equipment. 

**Tasks**
- [x] Optimisation pass -- remove all debug information
- [x] remove fn_taskAttack in WPs + ZEN
- [x] add fn_taskAssault to WPs + ZEN
- [x] add fn_taskRetreat
- [x] add fn_taskRetreat to WPs + ZEN

**Source request:** 
- Forced Waypoints https://github.com/nk3nny/LambsDanger/issues/21
- WIP thread https://github.com/nk3nny/LambsDanger/issues/42

**Comment by nk3nny** [comment]
@jokoho48 @diwako 
I would appreciate a quick look at the code. If there are no pressing concerns. I'll close this issue for v2.0

To my knowledge, there are no breaking errors. 

-k

**Comment by nk3nny** [comment]
https://github.com/nk3nny/LambsDanger/blob/master/addons/wp/functions/fnc_taskAssault.sqf

Perhaps one concern is that the 'Assault'moniker is passed around a little freely. Might be another naming scheme would be more suitable. *Shrug*
